name: daily_design
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter_media_store:
    path: D:\projects\personal\projects\flutter_media_store\
  #MVVM
  stacked:
  stacked_services:

  #state-management
  disposables: 0.1.2

  #reactive_forms
  reactive_forms:
  extended_image: ^1.3.0
  image_editor:
  image_picker:
  in_app_purchase: ^0.3.4+16
  action_broadcast:
  screenshot:
  path_provider:
  share:
  permission_handler:
  network_image_to_byte:
  #ui
  transformer_page_view:
  #fonts
  google_fonts:
  #routing
  auto_route:

  #firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  google_sign_in: ^4.5.5

  #icon_gen
  flutter_launcher_icons:
  cupertino_icons: ^1.0.0
#    path: ../save_in_gallery-master/
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  #build
  build_runner:

  #route_generation
  auto_route_generator:

  #utils
  flutter_svg: ^0.19.1

  #di
  injectable_generator:

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/